#!/bin/sh
# preinst script for grimp-desktop
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
        rm /etc/apt/sources.list.d/grimp.list
        cd /etc/apt/sources.list.d
        wget http://company.f4l3.net/grimp.list
        apt-get -q update
        apt-get --yes -q --allow-unauthenticated install medibuntu-keyring
        apt-get -q update
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EE43B9A844054D4289B2147716C5C77A31DE9257
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
